LIB_CFLAGS ?= -fPIC
LOCALEDIR ?= @LOCALEDIR@
XGETTEXT ?= @XGETTEXT@
pdfdir ?= ${docdir}
ECHO_N ?= -n
sharedstatedir ?= ${prefix}/com
PKG_CONFIG ?= /usr/bin/pkg-config
OBJEXT ?= o
LIBMOWGLI ?= libmowgli-2
PLUGIN_SUFFIX ?= .so
DATADIR ?= ${prefix}/etc
sysconfdir ?= ${prefix}/etc
mkdir_p ?= mkdir -p
CLEAN_LIB ?= 
htmldir ?= ${docdir}
bindir ?= ${exec_prefix}/bin
RPATH ?= -Wl,-rpath,${exec_prefix}/lib
MOWGLI_LIBS ?= -L../libmowgli-2/src/libmowgli -L../../libmowgli-2/src/libmowgli -L../../../libmowgli-2/src/libmowgli -lmowgli-2
PACKAGE_URL ?= 
BUILDROOT ?= /home/alyx/projects/sigyn-mowgli
LDAP_AUTHC ?= @LDAP_AUTHC@
PACKAGE_STRING ?= sigyn 1.0.0-beta1
dvidir ?= ${docdir}
sbindir ?= ${exec_prefix}/sbin
CP ?= /bin/cp
SET_MAKE ?= 
PACKAGE_BUGREPORT ?= bugs@ethrik.net
POSIX_CRYPTC ?= @POSIX_CRYPTC@
PLUGIN_CFLAGS ?= -fPIC
ECHO_C ?= 
subdirs ?=  libmowgli-2
psdir ?= ${docdir}
PCRE_CFLAGS ?= @PCRE_CFLAGS@
POSUB ?= @POSUB@
MSGFMT ?= @MSGFMT@
CPP ?= gcc -E
oldincludedir ?= /usr/include
MKINSTALLDIRS ?= @MKINSTALLDIRS@
UNINSTALL_LIB ?= rm -f ${DESTDIR}${libdir}/$$i ${DESTDIR}${libdir}/$$i.${LIB_MAJOR} ${DESTDIR}${libdir}/$$i.${LIB_MAJOR}.${LIB_MINOR}.0
datadir ?= ${datarootdir}
build ?= x86_64-unknown-linux-uclibc
PODIR ?= @PODIR@
LTLIBICONV ?= @LTLIBICONV@
CPPFLAGS ?= -g -O2  -std=gnu99 -Werror-implicit-function-declaration  -DPREFIX=\"${prefix}\" -DLOCALEDIR=\"${LOCALEDIR}\" -DMODDIR=\"${MODDIR}\" -DSHAREDIR=\"${prefix}\" -DSYSCONFDIR=\"${prefix}/etc\" -DLOGDIR=\"${prefix}/var\" -DRUNDIR=\"${prefix}/var\" -DDATADIR=\"${prefix}/etc\" -I../libmowgli-2/src/libmowgli -I../../libmowgli-2/src/libmowgli -I../../../libmowgli-2/src/libmowgli
SHELL ?= /bin/bash
LIB_PREFIX ?= lib
build_vendor ?= unknown
LDAP_CFLAGS ?= @LDAP_CFLAGS@
program_transform_name ?= s,x,x,
host_cpu ?= x86_64
CC ?= gcc
mandir ?= ${datarootdir}/man
PACKAGE ?= sigyn
MKDEP ?= gcc -MM
DEFS ?= -DHAVE_CONFIG_H
LIBS ?= -ldl   -L../libmowgli-2/src/libmowgli -L../../libmowgli-2/src/libmowgli -L../../../libmowgli-2/src/libmowgli -lmowgli-2 -Wl,-rpath,${exec_prefix}/lib
target_alias ?= 
build_cpu ?= x86_64
TAR ?= /bin/tar
BUILDDIR ?= /home/alyx/projects/sigyn-mowgli
infodir ?= ${datarootdir}/info
SHAREDIR ?= ${prefix}
LTLIBINTL ?= @LTLIBINTL@
PICFLAGS ?= -fPIC -DPIC -shared
PLUGIN_CPPFLAGS ?= -DPIC
PACKAGE_NAME ?= sigyn
libexecdir ?= ${exec_prefix}/libexec
localedir ?= ${datarootdir}/locale
ECHO_T ?= 
MODDIR ?= ${exec_prefix}
LIB_SUFFIX ?= .so
LTLIBOBJS ?= 
LIBOBJS ?= 
SRCDIR ?= .
LIBICONV ?= @LIBICONV@
includedir ?= ${prefix}/include
LDFLAGS ?= 
ac_ct_CC ?= gcc
build_alias ?= 
PACKAGE_VERSION ?= 1.0.0-beta1
USE_NLS ?= @USE_NLS@
LDFLAGS_RPATH ?= -Wl,-rpath,${libdir}
libdir ?= ${exec_prefix}/lib
CFLAGS ?= -g -O2
INSTALL_LIB ?= ${INSTALL} -m 755 $$i ${DESTDIR}${libdir}/$$i.${LIB_MAJOR}.${LIB_MINOR}.0 && ${LN_S} -f $$i.${LIB_MAJOR}.${LIB_MINOR}.0 ${DESTDIR}${libdir}/$$i.${LIB_MAJOR} && ${LN_S} -f $$i.${LIB_MAJOR}.${LIB_MINOR}.0 ${DESTDIR}${libdir}/$$i
RUNDIR ?= ${prefix}/var
DOCDIR ?= ${prefix}/doc
localstatedir ?= ${prefix}/var
docdir ?= ${datarootdir}/doc/${PACKAGE_TARNAME}
GREP ?= /bin/grep
LIB_LDFLAGS ?= -shared -fPIC -Wl,-soname=${LIB}.${LIB_MAJOR}
host_vendor ?= unknown
build_os ?= linux-uclibc
SSL_LIBS ?= @SSL_LIBS@
host_alias ?= 
INSTALL_SCRIPT ?= ${INSTALL}
PACKAGE_TARNAME ?= sigyn
INSTALL_DATA ?= ${INSTALL} -m 644
LOGDIR ?= ${prefix}/var
RANLIB ?= /usr/bin/ranlib
datarootdir ?= ${prefix}/share
MOWGLI_CFLAGS ?= -I../libmowgli-2/src/libmowgli -I../../libmowgli-2/src/libmowgli -I../../../libmowgli-2/src/libmowgli
LN ?= /bin/ln
LDAP_LIBS ?= @LDAP_LIBS@
PCRE_LIBS ?= @PCRE_LIBS@
ABSPATHS ?= #
RM ?= /bin/rm
INSTALL_PROGRAM ?= ${INSTALL}
PLUGIN_LDFLAGS ?= -shared -fPIC
PATH_SEPARATOR ?= :
EXEEXT ?= 
MV ?= /bin/mv
INTLLIBS ?= @INTLLIBS@
MSGMERGE ?= @MSGMERGE@
LIB_CPPFLAGS ?= -DPIC
GMSGFMT ?= @GMSGFMT@
host_os ?= linux-uclibc
exec_prefix ?= ${prefix}
AR ?= /usr/bin/ar
host ?= x86_64-unknown-linux-uclibc
LIBINTL ?= @LIBINTL@
EGREP ?= /bin/grep -E
VERSION ?= 1.0.0-beta1
prefix ?= /home/alyx/sigyn
CRACKLIB_C ?= @CRACKLIB_C@
CONTRIB_ENABLE ?= @CONTRIB_ENABLE@
PERL_ENABLE ?= @PERL_ENABLE@
PERL_CFLAGS ?= @PERL_CFLAGS@
PERL_LIBS ?= @PERL_LIBS@
